adocao_gestao/urls.py
from django.urls import path

from . import views

app_name = 'adocao_gestao'

urlpatterns = [
    path("cadastro-adocao/", views.cadastro_adocao, name="adote"),
    path('aprovar-adocao/<int:adocao_id>/', views.aprovar_desaprovar_adocao, name='aprovar_desaprovar_adocao'),
    path('lista-adocoes/', views.lista_adocoes, name='lista_adocoes'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')), #URL home, quando acessar o 'http://127.0.0.1:8000/' ou 'localhost:8000'
    path('animais/', include('cadastro_animal.urls')), 
    path('adocoes/', include('adocao_gestao.urls')), 
    path('usuarios/', include('cadastro_usuario.urls')) ,


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.views.generic import TemplateView


from home import views
from cadastro_animal.views import lista_animais 

app_name = 'home'

urlpatterns = [
    path("", lista_animais, name="home"),
    #pagina de pesquisa do cadastro_animais
    path("pesquisar-animais/", views.pesquisar_animais, name="pesquisar_animais"),
    # URL para a página estática
    path('sobre/', TemplateView.as_view(template_name='templates_home/sobre.html'), name='sobre'),
    path('contato/', TemplateView.as_view(template_name='templates_home/contato.html'), name='contato'),
]

templates/templates_gestaoadocao/adocao_list.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}

{% block title %}
Lista de solicitações de adoções
{% endblock %}

{% block content %}
<div class="d-grid gap-2 col-6 mx-auto mt-5">


    <h1 class="mb-4">Solicitações de Adoção</h1>

    {% if messages %}
    <div>
        {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% else %}alert-info{% endif %}">
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}

    <table class="table text-center">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Animal</th>
                <th>Data da solicitação</th>
                <th>Status</th>
                <th>Ação</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            {% for adocao in adocoes %}
            <tr>
                <td>{{ adocao.nome|capfirst  }}</td>
                <td>
                    {% if adocao.animal %}
                    {{ adocao.animal.nome|capfirst  }}
                    {% else %}
                    Não especificado
                    {% endif %}
                </td>
                <td>{{ adocao.data_solicitacao_formatada|capfirst }}</td>
                {% if adocao.get_solicitacao_status != 'Adoção aprovada' %}
                <td class="fw-bold">{{ adocao.get_solicitacao_status|capfirst  }}</td>
                {% else %}
                <td class="text-success fw-bold">{{ adocao.get_solicitacao_status|capfirst  }}</td>
                {% endif %}
                <td class="text-center align-middle">
                    <div class="d-flex justify-content-center gap-1">
                        {% if adocao.get_solicitacao_status != 'Adoção aprovada' %}
                        <a href="{% url 'adocao_gestao:aprovar_desaprovar_adocao' adocao.id %}"
                            class="btn btn-primary d-flex align-items-center justify-content-center">
                            <span class="material-symbols-outlined">
                                check_circle
                            </span>
                        </a>
                        {% else %}
                        <a class="btn btn-primary d-flex align-items-center justify-content-center disabled" >
                            <span class="material-symbols-outlined">
                                check_circle
                            </span>
                        </a>
                        <a href="{% url 'adocao_gestao:aprovar_desaprovar_adocao' adocao.id %}"
                            class="btn btn-danger d-flex align-items-center justify-content-center">
                            <span class="material-symbols-outlined">
                                cancel
                            </span>
                        </a>
                        {% endif %}
                    </div>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>

<a class="btn btn-outline-primary m-4" href="{% url 'home:home' %}" role="button">Voltar</a>
{% endblock %}

templates/templates_gestaoadocao/adotar.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}

{% block title %}
Cadastro de adoções
{% endblock %}

{% block content %}

<div class="d-grid gap-2 col-6 mx-auto mt-5">
    <h1 class="text-center">Solicitação de adoção</h1>

    {% if sucesso %}
    <div class="alert alert-success" role="alert">
        Solicitação enviada com sucesso! Logo entraremos em contato! 
    </div>
    {% endif %}

    {% if error %}
    <div class="alert alert-danger" role="alert">
        {{ error }}
    </div>
    {% endif %}

    <div class="mb-3 card">
        <div class="card-body">
            <form enctype="multipart/form-data"  action="" method="POST">
                {% csrf_token %}

                {% bootstrap_form form_adocao %}

                <div class="mt-4 text-center">
                    <button class="btn btn-outline-primary" type="submit">Enviar solicitação</button>
                </div>
            </form>
        </div>
    </div>

</div>

<a class="btn btn-outline-primary m-4" href="{% url 'home:home' %}" role="button">Voltar</a>

{% endblock %}