adocao_gestao/urls.py
from django.urls import path

from . import views

app_name = 'adocao_gestao'

urlpatterns = [
    path("cadastro-adocao/", views.cadastro_adocao, name="adote"),
    path('aprovar-adocao/<int:adocao_id>/', views.aprovar_desaprovar_adocao, name='aprovar_desaprovar_adocao'),
    path('lista-adocoes/', views.lista_adocoes, name='lista_adocoes'),
]

cadastro_animal/urls.py
from django.urls import path

from . import views

app_name = 'cadastro_animal'

urlpatterns = [
    path("cadastro-animal/", views.cadastro, name="cadastro_animal"),
    path('animal/<int:animal_id>/', views.detalhe_animal, name='detalhe_animal')
]

cadastro_usuario/urls.py
from django.urls import path

from . import views

app_name = 'cadastro_usuario'

urlpatterns = [
    path("registro/", views.cadastro_usuario, name="cadastro_usuario"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('lista-usuarios/', views.lista_usuarios, name='lista_usuarios'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')), #URL home, quando acessar o 'http://127.0.0.1:8000/' ou 'localhost:8000'
    path('animais/', include('cadastro_animal.urls')), 
    path('adocoes/', include('adocao_gestao.urls')), 
    path('usuarios/', include('cadastro_usuario.urls')) ,


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.views.generic import TemplateView


from home import views
from cadastro_animal.views import lista_animais 

app_name = 'home'

urlpatterns = [
    path("", lista_animais, name="home"),
    #pagina de pesquisa do cadastro_animais
    path("pesquisar-animais/", views.pesquisar_animais, name="pesquisar_animais"),
    # URL para a página estática
    path('sobre/', TemplateView.as_view(template_name='templates_home/sobre.html'), name='sobre'),
    path('contato/', TemplateView.as_view(template_name='templates_home/contato.html'), name='contato'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.db.models import Q

from cadastro_animal.views import CadastroAnimal


def pesquisar_animais(request):
    if 'pesquisa_query' in request.GET:
        pesquisa_query = request.GET['pesquisa_query']

        #fazendo pessquisa com multiplas palavra chaves e campos
        query_clean = Q(Q(nome__icontains = pesquisa_query) | Q(especie__icontains = pesquisa_query))
        animais = CadastroAnimal.objects.filter(query_clean, disponivel = True)

        #fazendo pesquisa só de um campo
        # animais = CadastroAnimal.objects.filter(nome__icontains = pesquisa_query)
        
        return render(request, 'templates_home/pagina_pesquisa.html', {'pesquisa_query':pesquisa_query , 'animais': animais})
    
    else:
        return render(request, 'templates_home/pagina_pesquisa.html', {})

templates/templates_home/contato.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}

{% block title %}
Contato
{% endblock %}

{% block content %}

<div class="d-grid gap-2 col-6 mx-auto mt-5">
    <h1 class="text-center mb-4">Entre em contato com a gente</h1>
    <div class="mb-3 card">
        <div class="card-body">
            <form enctype="multipart/form-data"  action="" method="POST">
                {% csrf_token %}

                
                <div class="row g-3">
                    <div class="col">
                        <div class="form-floating ">
                            <input type="text" class="form-control" id="floatingInput" placeholder="Nome">
                            <label for="floatingInput">Digite seu nome</label>
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-floating mb-3">
                            <input type="email" class="form-control" id="floatingPassword" placeholder="Password">
                            <label for="floatingPassword">Digite seu email</label>
                        </div>
            
                    </div>
                  </div>
                  <div class="form-floating mb-3">
                    <select class="form-select" id="floatingSelectGrid" >
                      <option selected>Selecione o assunto da mensagem</option>
                      <option value="1">Cadastro de adoção</option>
                      <option value="2">Problemas no cadastro de adoção</option>
                      <option value="3">Problemas no site</option>
                      <option value="3">Prazo para retorno da adoção</option>
                      <option value="5">Outro</option>
                    </select>
                    <label for="floatingSelectGrid">Escolha um assunto</label>
                  </div>
    
                <div class="form-floating">
                    <textarea class="form-control" placeholder="Mensagem" id="floatingTextarea2"
                        style="height: 200px"></textarea>
                    <label for="floatingTextarea2">Digite sua mensagem</label>
                </div>
    
                <div class="mt-4 text-center" >
                    <button class="btn btn-outline-primary" type="submit" style="width: 150px;">Enviar</button>
                </div>
            </form>

        </div>
    </div>
</div>

<a class="btn btn-outline-primary m-4" href="{% url 'home:home' %}" role="button">Voltar a home</a>

{% endblock %}

templates/templates_home/home.html
{% extends 'base.html' %}
{% load bootstrap5 static %}
{% bootstrap_css %}

{% block title %}Home{% endblock %}

{% block content %}

<div class="container mx-auto p-4">
    <h2 class="text-center text-primary py-3 rounded border border-primary display-6">
        Bem-vindos ao Abrigo Animal!
    </h2>
</div>

<div class="container my-4">
    <div class="row g-2">
        {% for animal in animais %}
        <div class="col-12 col-md-6 col-lg-4">
            {% if animal.galeria.first %}
            <div class="card text-white">
                <img src="{{ animal.galeria.first.imagem.url }}" alt="Imagem de {{ animal.nome|capfirst }}" width="auto"
                    height="260px" class="rounded">

                <div class="d-flex text-center card-img-overlay gap-4">
                    <a class="btn btn-primary detalhes-pet" href="{% url 'cadastro_animal:detalhe_animal' animal.id %}"
                        style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">
                        Ver detalhes
                    </a>
                    <a class="btn btn-success adotar-pet" href="{% url 'adocao_gestao:adote' %}"
                        style="--bs-btn-padding-y: 6px; --bs-btn-padding-x: 25px; --bs-btn-font-size: 16px;">
                        Adotar
                    </a>

                </div>
            </div>
            <div class=" mt-2">
                <h5 class="font-bold">{{ animal.nome|capfirst }}</h5>
                <p>{{ animal.idade }} anos | {{ animal.especie|capfirst }} | {{ animal.sexo|capfirst }}</p>
            </div>
            {% else %}
            <div class="card bg-dark text-white">
                <img src="{% static 'img/default.png' %}" alt="Imagem de {{ animal.nome|capfirst }}"
                    class="card-img imagem-responsiva">
                <div class="card-img-overlay">
                    <h5 class="card-title">Ver detalhes</h5>

                </div>
            </div>
            {% endif %}
        </div>
        {% empty %}
        <h1 class="text-center">Nenhum animal cadastrado.</h1>
        {% endfor %}
    </div>
</div>

<div class="container mx-auto p-4">
    <h2 class="text-center text-primary py-3 rounded border border-primary display-6">
        Adote. Não Compre.
    </h2>
</div>

{% endblock %}

templates/templates_home/login-Admin-Vet_Ajudante.html
{% load static %}
{% load user_permissao %}

<!-- Botão de login/logout com dropdown alinhado à direita -->
<div class="d-flex ms-auto">
  <div class="btn-group">
    <button type="button" class="btn btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
      Olá, {{ user.first_name }}!
    </button>

    <!-- Menu de opções do usuário -->
    <ul class="dropdown-menu dropdown-menu-lg-end">
      <li>
        <a class="dropdown-item d-flex align-items-center" href="{% url 'cadastro_animal:cadastro_animal' %}">
          <span class="material-symbols-outlined me-2">add_circle</span> Cadastro de pet
        </a>
      </li>
      <li><hr class="dropdown-divider"></li>
      <li>
        <a class="dropdown-item d-flex align-items-center" href="{% url 'adocao_gestao:lista_adocoes' %}">
          <span class="material-symbols-outlined me-2">list_alt</span> Solicitações de adoções
        </a>
      </li>
      <li><hr class="dropdown-divider"></li>
      <li>
        <a class="dropdown-item d-flex align-items-center" href="{% url 'cadastro_usuario:cadastro_usuario' %}">
          <span class="material-symbols-outlined me-2">add_circle</span> Cadastro de usuário
        </a>
      </li>
      <li>
        <a class="dropdown-item d-flex align-items-center" href="{% url 'cadastro_usuario:lista_usuarios' %}">
          <span class="material-symbols-outlined me-2">patient_list</span> Lista de usuários
        </a>
      </li>
      <li><hr class="dropdown-divider"></li>
      <li>
        <a class="dropdown-item d-flex align-items-center" href="{% url 'cadastro_usuario:logout' %}">
          <span class="material-symbols-outlined me-2">logout</span> Logout
        </a>
      </li>
    </ul>
  </div>
</div>

templates/templates_home/login-voluntario.html
{% load static %}
{% load user_permissao %}

      <!-- Botão de login/logout com dropdown alinhado à direita -->
      <div class="d-flex ms-auto">

        <!-- abre um modal com algumas infos do site -->
        <a href="" class="nav-link d-flex align-items-center pe-auto" data-bs-toggle="modal" data-bs-target="#helpModal">
          <span class="material-symbols-outlined me-2" >help</span>
        </a>
        <div class="btn-group">

          <button type="button" class="btn btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown"
          data-bs-display="static" aria-expanded="false">
          Olá, {{ user.first_name }}!
        </button>

        <!-- inicio do menu usuario-->
        <ul class="dropdown-menu dropdown-menu-lg-end">
          <li>
            <a class="dropdown-item d-flex align-items-center" href="{% url 'cadastro_usuario:logout' %}">
              <span class="material-symbols-outlined me-2">logout</span> Fazer Logout
            </a>
          </li>
                  
        </ul>
      <!-- fim do menu dropdown -->
      </div>
</div>

templates/templates_home/modal_help.html
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}

<!-- Scrollable modal -->
<div class="modal-dialog modal-dialog-scrollable" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="staticBackdropLabel">Modal title</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            ...
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="button" class="btn btn-primary">Understood</button>
          </div>
        </div>
      </div>
  </div>

templates/templates_home/pagina_pesquisa.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}

{% block title %}
Pesquisar um animal
{% endblock %}

{% block content %}



<div class="container my-2">
    {% if pesquisa_query %}
    <div class="mt-5">
        <div class="text-center">
            <h1 class="text-center mb-4">Você pesquisou... <strong>{{ pesquisa_query|capfirst }}</strong></h1>
        </div>
        <hr>

        <div class="row g-4">
            {% for animal in animais %}
            <div class="col-12 col-md-6 col-lg-4">
                <div class="card h-100">
                    {% if animal.galeria.first %}
                    <img src="{{ animal.galeria.first.imagem.url }}" class="card-img-top" alt="Imagem de {{ animal.nome|capfirst }}" style="height: 200px; object-fit: cover;">
                    {% else %}
                    <img src="{% static 'img\default.png' %}" class="card-img-top" alt="Imagem de {{ animal.nome|capfirst }}" style="height: 150px; object-fit: cover;">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title display-6">{{ animal.nome|capfirst }}</h5>
                        <p class="card-text">{{ animal.idade }} anos | {{ animal.especie|capfirst }} | {{ animal.sexo|capfirst }}</p>
                    <!-- Botão de adoção -->
                     <div class="d-flex">
                        <div class="p-2">
                            <a href="{% url 'cadastro_animal:detalhe_animal' animal.id %}" class="btn btn-outline-primary">Ver mais </a>
                        </div>
                        <div class="p-2">
                            <a href="{% url 'adocao_gestao:adote' %}" class="btn btn-outline-success">Adotar </a>
                        </div>
                   </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <p class="text-center">Nenhum animal cadastrado.</p>
            {% endfor %}
        </div>

    </div>

    {% else %}
    <div class="d-flex flex-column justify-content-center align-items-center min-vh-100 text-center">
        <h1 class="display-6">Desculpe... <br>Você precisa pesquisar um animal antes!</h1>
        <div>
            <img src="{% static 'img/img_cachorro_pesquisaelse.png' %}" alt="Imagem de cachorro" class="img-fluid"
                style="max-width: 400px;">
        </div>
    </div>
    {% endif %}
</div>

<a class="btn btn-outline-primary m-4" href="{% url 'home:home' %}" role="button">Voltar</a>
{% endblock %}