adocao_gestao/urls.py
from django.urls import path

from . import views

app_name = 'adocao_gestao'

urlpatterns = [
    path("cadastro-adocao/", views.cadastro_adocao, name="adote"),
    path('aprovar-adocao/<int:adocao_id>/', views.aprovar_desaprovar_adocao, name='aprovar_desaprovar_adocao'),
    path('lista-adocoes/', views.lista_adocoes, name='lista_adocoes'),
]

cadastro_usuario/urls.py
from django.urls import path

from . import views

app_name = 'cadastro_usuario'

urlpatterns = [
    path("registro/", views.cadastro_usuario, name="cadastro_usuario"),
    path('login/', views.login_view, name="login"),
    path('logout/', views.logout_view, name="logout"),
    path('lista-usuarios/', views.lista_usuarios, name='lista_usuarios'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')), #URL home, quando acessar o 'http://127.0.0.1:8000/' ou 'localhost:8000'
    path('animais/', include('cadastro_animal.urls')), 
    path('adocoes/', include('adocao_gestao.urls')), 
    path('usuarios/', include('cadastro_usuario.urls')) ,


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.views.generic import TemplateView


from home import views
from cadastro_animal.views import lista_animais 

app_name = 'home'

urlpatterns = [
    path("", lista_animais, name="home"),
    #pagina de pesquisa do cadastro_animais
    path("pesquisar-animais/", views.pesquisar_animais, name="pesquisar_animais"),
    # URL para a página estática
    path('sobre/', TemplateView.as_view(template_name='templates_home/sobre.html'), name='sobre'),
    path('contato/', TemplateView.as_view(template_name='templates_home/contato.html'), name='contato'),
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render
from django.db.models import Q

from cadastro_animal.views import CadastroAnimal


def pesquisar_animais(request):
    if 'pesquisa_query' in request.GET:
        pesquisa_query = request.GET['pesquisa_query']

        #fazendo pessquisa com multiplas palavra chaves e campos
        query_clean = Q(Q(nome__icontains = pesquisa_query) | Q(especie__icontains = pesquisa_query))
        animais = CadastroAnimal.objects.filter(query_clean, disponivel = True)

        #fazendo pesquisa só de um campo
        # animais = CadastroAnimal.objects.filter(nome__icontains = pesquisa_query)
        
        return render(request, 'templates_home/pagina_pesquisa.html', {'pesquisa_query':pesquisa_query , 'animais': animais})
    
    else:
        return render(request, 'templates_home/pagina_pesquisa.html', {})

templates/base.html
<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">


  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="https://getbootstrap.com/docs/5.3/assets/css/docs.css" rel="stylesheet">

  <!-- Google Material Icons -->
  <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet">

  {% load static %}
  <!-- Custom Stylesheet -->
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">

  <!-- Title -->
  <title>Abrigo Animal | {% block title %}Página inicial{% endblock %}</title>
</head>

<body class="poppins-regular">

  <!-- Navigation -->
  {% include 'nav.html' %}

  <!-- Main Content -->
  <main class="container my-4">

    <!-- inicio do alerta toast -->

    {% if messages %} <!-- se tiver mensagens ativa o toast-->
    {% for message in messages %} <!-- pega as mensagens disponiveis -->
    
    {% if 'success' in message.tags %} <!-- se for sucesso -->
    <div id="liveToast"
      class="toast toast-alerts align-items-center text-white bg-{{message.tags}} z-3 position-absolute end-0 fade "
      role="alert" aria-live="assertive" aria-atomic="true">
      <div class="toast-header">
        <strong class="me-auto">


          <svg class="bd-placeholder-img rounded" width="20" height="20" viewBox="0 0 24 24" fill="none"
            xmlns="http://www.w3.org/2000/svg">
            <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
            <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
            <g id="SVGRepo_iconCarrier">
              <path fill-rule="evenodd" clip-rule="evenodd"
                d="M22 12C22 17.5228 17.5228 22 12 22C6.47715 22 2 17.5228 2 12C2 6.47715 6.47715 2 12 2C17.5228 2 22 6.47715 22 12ZM16.0303 8.96967C16.3232 9.26256 16.3232 9.73744 16.0303 10.0303L11.0303 15.0303C10.7374 15.3232 10.2626 15.3232 9.96967 15.0303L7.96967 13.0303C7.67678 12.7374 7.67678 12.2626 7.96967 11.9697C8.26256 11.6768 8.73744 11.6768 9.03033 11.9697L10.5 13.4393L12.7348 11.2045L14.9697 8.96967C15.2626 8.67678 15.7374 8.67678 16.0303 8.96967Z"
                fill="#000000"></path>
            </g>
          </svg>
          Sucesso!

          {% else %} <!-- para o erro -->

          <svg class="bd-placeholder-img rounded" width="20" height="20" viewBox="0 0 24 24" fill="none"
            xmlns="http://www.w3.org/2000/svg">
            <g id="SVGRepo_bgCarrier" stroke-width="0"></g>
            <g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g>
            <g id="SVGRepo_iconCarrier">
              <path fill-rule="evenodd" clip-rule="evenodd"
                d="M1 12C1 5.92487 5.92487 1 12 1C18.0751 1 23 5.92487 23 12C23 18.0751 18.0751 23 12 23C5.92487 23 1 18.0751 1 12ZM7.75736 7.05025C8.14788 6.65973 8.78105 6.65973 9.17157 7.05025L12 9.87868L14.8284 7.05025C15.219 6.65973 15.8521 6.65973 16.2426 7.05025L16.9497 7.75736C17.3403 8.14788 17.3403 8.78105 16.9497 9.17157L14.1213 12L16.9497 14.8284C17.3403 15.219 17.3403 15.8521 16.9497 16.2426L16.2426 16.9497C15.8521 17.3403 15.219 17.3403 14.8284 16.9497L12 14.1213L9.17157 16.9497C8.78105 17.3403 8.14788 17.3403 7.75736 16.9497L7.05025 16.2426C6.65973 15.8521 6.65973 15.219 7.05025 14.8284L9.87868 12L7.05025 9.17157C6.65973 8.78105 6.65973 8.14788 7.05025 7.75736L7.75736 7.05025Z"
                fill="#000000"></path>
            </g>
          </svg>

          Erro!

          {% endif %}
        </strong>
        <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
      </div>

      <div class="toast-body">
        <i>{{ message }}</i> <!-- mostra a mensagem do return lá da view -->
      </div>

      {% endfor %}
      {% endif %}

    </div> <!-- fim do alerta toast -->


    {% block content %}{% endblock %} <!-- conteudo de outras paginas -->


  </main>


  <!-- Footer -->
  {% include 'footer.html' %}


  <!-- Scripts -->
  {% block scripts %}
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
  <script src="{% static 'js/scripts.js' %}"></script>
  {% endblock %}

</body>

</html>

templates/contato.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}

{% block title %}
Contato
{% endblock %}

{% block content %}

<div class="d-grid gap-2 col-6 mx-auto mt-5">
    <h1 class="text-center">Entre em contato com a gente</h1>
    <div class="mb-3 card">
        <div class="card-body">
            <form enctype="multipart/form-data"  action="" method="POST">
                {% csrf_token %}

                
                <div class="row g-3">
                    <div class="col">
                        <div class="form-floating ">
                            <input type="text" class="form-control" id="floatingInput" placeholder="Nome">
                            <label for="floatingInput">Digite seu nome</label>
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-floating mb-3">
                            <input type="email" class="form-control" id="floatingPassword" placeholder="Password">
                            <label for="floatingPassword">Digite seu email</label>
                        </div>
            
                    </div>
                  </div>
                  <div class="form-floating mb-3">
                    <select class="form-select" id="floatingSelectGrid" >
                      <option selected>Selecione o assunto da mensagem</option>
                      <option value="1">Cadastro de adoção</option>
                      <option value="2">Problemas no cadastro de adoção</option>
                      <option value="3">Problemas no site</option>
                      <option value="3">Prazo para retorno da adoção</option>
                      <option value="5">Outro</option>
                    </select>
                    <label for="floatingSelectGrid">Escolha um assunto</label>
                  </div>
    
                <div class="form-floating">
                    <textarea class="form-control" placeholder="Mensagem" id="floatingTextarea2"
                        style="height: 200px"></textarea>
                    <label for="floatingTextarea2">Digite sua mensagem</label>
                </div>
    
                <div class="mt-4 text-center" >
                    <button class="btn btn-outline-primary" type="submit" style="width: 150px;">Enviar</button>
                </div>
            </form>

        </div>
    </div>
</div>

<a class="btn btn-outline-primary m-4" href="{% url 'home' %}" role="button">Voltar a home</a>

{% endblock %}

templates/footer.html
<footer class="footer bg-body-tertiary text-center text-lg-start shadow-sm mt-auto">
    <div class="text-center p-4" style="background-color: rgba(0, 0, 0, 0.05);">
        © 2024 Copyright <br> 
        <a class="text-body" href="https://github.com/Andiichi" target="_blank">Andichii Dev</a>
    </div>
</footer>

templates/home.html
{% extends 'base.html' %}
{% load bootstrap5 static %}
{% bootstrap_css %}

{% block title %}Home{% endblock %}

{% block content %}

{% if messages %}
<div id="liveToast" class="toast align-items-center position-fixed" role="alert" aria-live="assertive"
    aria-atomic="true" data-bs-autohide="true">
    <div class="d-flex">
        <div class="toast-body">
            {% for message in messages %}
            <strong>{{ message }}</strong>
            {% endfor %}
        </div>
        <button type="button" class="btn-close me-2 m-auto" data-bs-dismiss="toast" aria-label="Close"></button>
    </div>
</div>
{% endif %}

<div class="container mx-auto p-4">
    <h2 class="text-center text-primary py-3 rounded border border-primary display-6">
        Bem-vindos ao Abrigo Animal!
    </h2>
</div>

<div class="container my-4">
    <div class="row g-2">
        {% for animal in animais %}
        <div class="col-12 col-md-6 col-lg-4">
            {% if animal.galeria.first %}
            <div class="card text-white">
                <img src="{{ animal.galeria.first.imagem.url }}" alt="Imagem de {{ animal.nome|capfirst }}" width="auto"
                    height="260px" class="rounded">

                <div class="d-flex text-center card-img-overlay gap-4">
                    <a class="btn btn-primary detalhes-pet" href="{% url 'detalhe_animal' animal.id %}"
                        style="--bs-btn-padding-y: .25rem; --bs-btn-padding-x: .5rem; --bs-btn-font-size: .75rem;">
                        Ver detalhes
                    </a>
                    <a class="btn btn-success adotar-pet" href="{% url 'adocao_gestao:adote' %}"
                        style="--bs-btn-padding-y: 6px; --bs-btn-padding-x: 25px; --bs-btn-font-size: 16px;">
                        Adotar
                    </a>

                </div>
            </div>
            <div class=" mt-2">
                <h5 class="font-bold">{{ animal.nome|capfirst }}</h5>
                <p>{{ animal.idade }} anos | {{ animal.especie|capfirst }} | {{ animal.sexo|capfirst }}</p>
            </div>
            {% else %}
            <div class="card bg-dark text-white">
                <img src="{% static 'img/default.png' %}" alt="Imagem de {{ animal.nome|capfirst }}"
                    class="card-img imagem-responsiva">
                <div class="card-img-overlay">
                    <h5 class="card-title">Ver detalhes</h5>

                </div>
            </div>
            {% endif %}
        </div>
        {% empty %}
        <h1 class="text-center">Nenhum animal cadastrado.</h1>
        {% endfor %}
    </div>
</div>

<div class="container mx-auto p-4">
    <h2 class="text-center text-primary py-3 rounded border border-primary display-6">
        Adote. Não Compre.
    </h2>
</div>




{% endblock %}

templates/login-Admin-Vet_Ajudante.html
{% load static %}
{% load user_permissao %}

<!-- Botão de login/logout com dropdown alinhado à direita -->
<div class="d-flex ms-auto">
  <div class="btn-group">
    <button type="button" class="btn btn-outline-primary dropdown-toggle" data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
      Olá, {{ user.first_name }}!
    </button>

    <!-- Menu de opções do usuário -->
    <ul class="dropdown-menu dropdown-menu-lg-end">
      <li>
        <a class="dropdown-item d-flex align-items-center" href="{% url 'cadastro_animal' %}">
          <span class="material-symbols-outlined me-2">add_circle</span> Cadastro de pet
        </a>
      </li>
      <li><hr class="dropdown-divider"></li>
      <li>
        <a class="dropdown-item d-flex align-items-center" href="{% url 'adocao_gestao:lista_adocoes' %}">
          <span class="material-symbols-outlined me-2">list_alt</span> Solicitações de adoções
        </a>
      </li>
      <li><hr class="dropdown-divider"></li>
      <li>
        <a class="dropdown-item d-flex align-items-center" href="{% url 'cadastro_usuario:cadastro_usuario' %}">
          <span class="material-symbols-outlined me-2">add_circle</span> Cadastro de usuário
        </a>
      </li>
      <li>
        <a class="dropdown-item d-flex align-items-center" href="{% url 'cadastro_usuario:lista_usuarios' %}">
          <span class="material-symbols-outlined me-2">patient_list</span> Lista de usuários
        </a>
      </li>
      <li><hr class="dropdown-divider"></li>
      <li>
        <a class="dropdown-item d-flex align-items-center" href="{% url 'cadastro_usuario:logout' %}">
          <span class="material-symbols-outlined me-2">logout</span> Logout
        </a>
      </li>
    </ul>
  </div>
</div>

templates/nav.html
{% load static %}
{% load user_permissao %}


<nav class="container-fluid navbar navbar-expand-lg bg-light shadow-sm px-5 py-3">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01"
        aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse justify-content-center" id="navbarTogglerDemo01">
        <a class="navbar-brand me-5 barrio-regular" href="/">Abrigo Animal</a>

        <ul class="navbar-nav d-flex align-items-center gap-3">
            <li class="nav-item traco-bottom">
                <a class="nav-link d-flex align-items-center" href="/">Home</a>
            </li>
            <li class="nav-item traco-bottom">
                <a class="nav-link d-flex align-items-center" href="{% url 'adocao_gestao:adote' %}">Adote</a>
            </li>
            <li class="nav-item traco-bottom">
                <a class="nav-link d-flex align-items-center" href="{% url 'home:sobre' %}">Sobre</a>
            </li>
            <li class="nav-item traco-bottom">
                <a class="nav-link d-flex align-items-center" href="{% url 'home:contato' %}">Contato</a>
            </li>
        </ul>

        <div class="d-flex ms-auto">
            <a href="#" class="nav-link d-flex align-items-center pe-auto" data-bs-toggle="modal"
                data-bs-target="#helpModal" data-bs-title="Ajuda">
                <span class="material-symbols-outlined me-2" >help</span>
            </a>

            <div class="px-2">
                <form class="d-flex align-items-center" role="search" action="{% url 'home:pesquisar_animais' %}">
                    <div class="input-group rounded-search">
                        <input class="form-control rounded-start" type="search" placeholder="Pesquisar um pet..."
                            aria-label="Search" name="pesquisa_query">
                        <button class="input-group-text bg-primary text-white rounded-end border-0" type="submit">
                            <span class="material-symbols-outlined icon-search">search</span>
                        </button>
                    </div>
                </form>
            </div>


            <!-- condições para aparecer os logins de acordo com o nivel do usuario ***provisorio  -->
            {% if user|has_group:"Administrador" %}
            {% include 'templates_home/login-Admin-Vet_Ajudante.html' %}
            {% elif user|has_group:"Vet_Ajudante" %}
            {% include 'templates_home/login-Admin-Vet_Ajudante-admin.html' %}
            {% elif user|has_group:"Voluntários" %}
            {% include 'templates_home/login-voluntario.html' %}
            {% else %}

            
            <button type="button" class="btn btn-outline-primary dropdown-toggle d-flex align-items-center"
                data-bs-toggle="dropdown" data-bs-display="static" aria-expanded="false">
                <span class="material-symbols-outlined">person</span> Login
            </button>
            <ul class="dropdown-menu dropdown-menu-lg-end">
                <li>
                    <a class="dropdown-item d-flex align-items-center" href="{% url 'cadastro_usuario:login' %}">
                        <span class="material-symbols-outlined me-2">account_circle</span> Fazer login
                    </a>
                </li>
                <li>
                    <hr class="dropdown-divider">
                </li>
                <li>
                    <a href="#" class="dropdown-item d-flex align-items-center" data-bs-toggle="modal"
                        data-bs-target="#helpModalUser">
                        <span class="material-symbols-outlined me-2">help</span> Ajuda login
                    </a>
                </li>
            </ul>
            {% endif %}
        </div>
    </div>
</nav>

<!-- Modais de Ajuda -->
<div class="modal fade" id="helpModal" tabindex="-1" aria-labelledby="helpModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="helpModalLabel">Ajuda do Site</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Aqui você encontra informações sobre como usar o site.</p>
                <ul>
                    <li>Para navegar, use o menu superior.</li>
                    <li>Para ver detalhes dos itens, clique no botão correspondente.</li>
                    <li>Se precisar de suporte, entre em contato através da seção de Contato.</li>
                </ul>
                <strong>Att,<br> Direção</strong>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary" data-bs-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="helpModalUser" tabindex="-1" aria-labelledby="helpModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="helpModalLabel">Ajuda para login</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <h3 class="fs-2">Quem tem permissão:</h3>
                <p>Para ter acesso à parte administrativa é necessário realizar o login.</p>
                <ul>
                    <li>Voluntários que têm seus cadastros feitos ou que receberam o e-mail.</li>
                    <li>Veterinários contratados e Voluntários.</li>
                    <li>Funcionários do abrigo.</li>
                </ul>
                <strong>Att,<br> Direção</strong>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline-primary" data-bs-dismiss="modal">Fechar</button>
            </div>
        </div>
    </div>
</div>

templates/pagina_pesquisa.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}

{% block title %}
Pesquisar um animal
{% endblock %}

{% block content %}



<div class="container my-2">
    {% if pesquisa_query %}
    <div class="mt-5">
        <div class="text-center">
            <h1 class="text-center mb-4">Você pesquisou... <strong>{{ pesquisa_query|capfirst }}</strong></h1>
        </div>
        <hr>

        <div class="row g-4">
            {% for animal in animais %}
            <div class="col-12 col-md-6 col-lg-4">
                <div class="card h-100">
                    {% if animal.galeria.first %}
                    <img src="{{ animal.galeria.first.imagem.url }}" class="card-img-top" alt="Imagem de {{ animal.nome|capfirst }}" style="height: 200px; object-fit: cover;">
                    {% else %}
                    <img src="{% static 'img\default.png' %}" class="card-img-top" alt="Imagem de {{ animal.nome|capfirst }}" style="height: 150px; object-fit: cover;">
                    {% endif %}
                    <div class="card-body">
                        <h5 class="card-title display-6">{{ animal.nome|capfirst }}</h5>
                        <p class="card-text">{{ animal.idade }} anos | {{ animal.especie|capfirst }} | {{ animal.sexo|capfirst }}</p>
                    <!-- Botão de adoção -->
                     <div class="d-flex">
                        <div class="p-2">
                            <a href="{% url 'detalhe_animal' animal.id %}" class="btn btn-outline-primary">Ver mais </a>
                        </div>
                        <div class="p-2">
                            <a href="{% url 'adocao_gestao:adote' %}" class="btn btn-outline-success">Adotar </a>
                        </div>
                   </div>
                    </div>
                </div>
            </div>
            {% empty %}
            <p class="text-center">Nenhum animal cadastrado.</p>
            {% endfor %}
        </div>

    </div>

    {% else %}
    <div class="d-flex flex-column justify-content-center align-items-center min-vh-100 text-center">
        <h1 class="display-6">Desculpe... <br>Você precisa pesquisar um animal antes!</h1>
        <div>
            <img src="{% static 'img/img_cachorro_pesquisaelse.png' %}" alt="Imagem de cachorro" class="img-fluid"
                style="max-width: 400px;">
        </div>
    </div>
    {% endif %}
</div>

{% endblock %}