adocao_gestao/urls.py
from django.urls import path

from . import views

app_name = 'adocao_gestao'

urlpatterns = [
    path("cadastro-adocao/", views.cadastro_adocao, name="adote"),
    path('aprovar-adocao/<int:adocao_id>/', views.aprovar_desaprovar_adocao, name='aprovar_desaprovar_adocao'),
    path('lista-adocoes/', views.lista_adocoes, name='lista_adocoes'),
]

cadastro_animal/urls.py
from django.urls import path

from . import views

app_name = 'cadastro_animal'

urlpatterns = [
    path("cadastro-animal/", views.cadastro, name="cadastro_animal"),
    path('animal/<int:animal_id>/', views.detalhe_animal, name='detalhe_animal')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')), #URL home, quando acessar o 'http://127.0.0.1:8000/' ou 'localhost:8000'
    path('animais/', include('cadastro_animal.urls')), 
    path('adocoes/', include('adocao_gestao.urls')), 
    path('usuarios/', include('cadastro_usuario.urls')) ,


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from django.views.generic import TemplateView


from home import views
from cadastro_animal.views import lista_animais 

app_name = 'home'

urlpatterns = [
    path("", lista_animais, name="home"),
    #pagina de pesquisa do cadastro_animais
    path("pesquisar-animais/", views.pesquisar_animais, name="pesquisar_animais"),
    # URL para a página estática
    path('sobre/', TemplateView.as_view(template_name='templates_home/sobre.html'), name='sobre'),
    path('contato/', TemplateView.as_view(template_name='templates_home/contato.html'), name='contato'),
]

cadastro_animal/models.py
from django.db import models
import os
from django.conf import settings
from django.utils import timezone


def upload_to_image(instance, filename):
    # Verificar se a instância é do tipo CadastroAnimal
    if isinstance(instance, CadastroAnimal):
        # Verificar se a instância já foi salva e tem um ID
        if instance.id:
            # Formatar o caminho com ID e nome em minúsculo
            return os.path.join('galeria', instance.nome.lower(), f'{instance.id}_{instance.nome.lower()}_{filename}')
        else:
            # Caso o ID ainda não esteja disponível, salvar apenas com o nome
            return os.path.join('galeria', instance.nome.lower(), filename)
    
    # Verificar se a instância é do tipo GaleriaAnimal (relacionada ao CadastroAnimal)
    elif hasattr(instance, 'animal') and isinstance(instance.animal, CadastroAnimal):
        # Se o ID do animal está disponível
        if instance.animal.id:
            return os.path.join('galeria', instance.animal.nome.lower(), f'{instance.animal.id}_{instance.animal.nome.lower()}_{filename}')
        else:
            return os.path.join('galeria', instance.animal.nome.lower(), filename)
    
    return os.path.join('galeria', 'default', filename)



class CadastroAnimal(models.Model):
    SEXO_CHOICES = [
        ('macho', 'Macho'),
        ('fêmea', 'Fêmea'),
    ]
    ESPECIE_CHOICES = [
        ('cachorro', 'Cachorro'),
        ('gato', 'Gato'),
    ]

    nome = models.CharField(max_length=75)
    idade = models.PositiveIntegerField()
    sexo = models.CharField(max_length=10, choices=SEXO_CHOICES, default='macho')
    especie = models.CharField(max_length=10, choices=ESPECIE_CHOICES, default='cachorro')
    disponivel = models.BooleanField(default=True)
    data_criacao = models.DateTimeField(auto_now_add=True)
    

    class Meta:
        verbose_name = 'Cadastro de Animal'
        verbose_name_plural = 'Cadastro de Animais'
        ordering = ['-nome']

    def __str__(self):
        return self.nome


class GaleriaAnimal(models.Model):
    animal = models.ForeignKey(CadastroAnimal, on_delete=models.CASCADE, related_name='galeria')
    imagem = models.ImageField(upload_to=upload_to_image, blank=True, null=True)


    def __str__(self):
        return f'Imagem de {self.animal.nome}'

cadastro_animal/forms.py
from django import forms

from .models import CadastroAnimal, GaleriaAnimal


class FormCadastroAnimal(forms.ModelForm):
    class Meta:
        model = CadastroAnimal
        fields = ['nome', 'idade', 'sexo', 'especie']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Digite o nome do animal'}),
            'idade': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Idade do animal'}),
            'sexo': forms.Select(attrs={'class': 'form-select'}),
            'especie': forms.Select(attrs={'class': 'form-select'}),
        }


class GaleriaAnimalForm(forms.ModelForm):
    class Meta:
        model = GaleriaAnimal
        fields = ['imagem']

cadastro_animal/views.py
from django.shortcuts import render, get_object_or_404
import os
from django.utils import timezone
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from .forms import FormCadastroAnimal
from .models import GaleriaAnimal, CadastroAnimal

                     
def lista_animais(request):
    animais = CadastroAnimal.objects.filter(disponivel = True)
    
    return render(request, 'templates_home/home.html', {'animais': animais})

def cadastro(request):
    if request.method == 'POST':
        form_animal = FormCadastroAnimal(request.POST, request.FILES)
        animal_imagem = request.FILES.getlist('animal_imagem')

        if form_animal.is_valid():
            animal = form_animal.save(commit=False)  # Não salva ainda

           # Deixar os campos de nome e raça em minúsculo
            animal.nome = animal.nome.lower()
            animal.save()  # Salve o animal primeiro para gerar o ID

            # Salvar a data de criação
            data_criacao = timezone.now()
            data_formatada = data_criacao.strftime('%Y%m%d')  # Formato: YYYYMMDD

            # Criar o caminho da nova pasta
            nome_pasta = f"{animal.nome}"
            caminho_pasta = os.path.join(settings.MEDIA_ROOT, 'galeria', nome_pasta)
            os.makedirs(caminho_pasta, exist_ok=True)  # Cria a pasta se não existir


             # Salva as imagens
            for i, imagem in enumerate(animal_imagem):
                # Novo nome do arquivo com o nome do animal e data de criação (e índice para evitar conflito)
                novo_nome_arquivo = f"{animal.nome}_{data_formatada}_{i+1}.jpg"

                # Cria uma instância de FileSystemStorage para salvar no caminho da nova pasta
                fs = FileSystemStorage(location=caminho_pasta)

                # Salva a imagem no novo diretório com o nome ajustado
                caminho_imagem_salva = fs.save(novo_nome_arquivo, imagem)

                # Salva a referência da imagem no banco de dados
                GaleriaAnimal.objects.create(
                    animal=animal, 
                    imagem=os.path.join('galeria', nome_pasta, novo_nome_arquivo)
                )

            # Define sucesso como True
            contexto = {
                'form_animal': FormCadastroAnimal(),  # Reseta o formulário após o envio
                'sucesso': True
            }
            return render(request, 'templates_cadastroanimal/cadastro_animal.html', contexto)
        else:
            contexto = {
                'form_animal': form_animal,
                'error': 'Erro ao cadastrar animal. Verifique os dados informados.'
            }
            return render(request, 'templates_cadastroanimal/cadastro_animal.html', contexto)
    
    else:
        form_animal = FormCadastroAnimal()
        return render(request, 'templates_cadastroanimal/cadastro_animal.html', {'form_animal': form_animal})

                                        
def detalhe_animal(request, animal_id):
    # Busca o animal pelo ID, ou retorna 404 se não for encontrado
    animal = get_object_or_404(CadastroAnimal, id=animal_id)
    
    # Renderiza o template e passa o objeto `animal` como contexto
    return render(request, 'templates_cadastroanimal/detalhe_animal.html', {'animal': animal})

    

templates/templates_cadastroanimal/cadastro_animal.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}

{% block title %}
Cadastro de animais
{% endblock %}

{% block content %}

<div class="d-grid gap-2 col-6 mx-auto mt-5">
    <h1 class="text-center">Cadastro de animal</h1>

    {% if sucesso %}
    <div class="alert alert-success" role="alert">
        Animal cadastrado com sucesso!
    </div>
    {% endif %}

    {% if error %}
    <div class="alert alert-danger" role="alert">
        {{ error }}
    </div>
    {% endif %}

    <div class="mb-3 card mx-auto" style="height: auto; width: 650px;">
        <div class="card-body" >
            <form enctype="multipart/form-data" action="" method="POST">
                {% csrf_token %}

                <!-- Nome e Idade -->
                <div class="row g-3">
                    <div class="col">
                        <div class="form-floating">
                            {{ form_animal.nome }}
                            <label for="id_nome">Nome do animal</label>
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-floating">
                            {{ form_animal.idade }}
                            <label for="id_idade">Idade do animal</label>
                        </div>
                    </div>
                </div>

                <!-- Sexo e Espécie -->
                <div class="row g-3 mt-3">
                    <div class="col">
                        <div class="form-floating">
                            {{ form_animal.sexo }}
                            <label for="id_sexo">Sexo</label>
                        </div>
                    </div>
                    <div class="col">
                        <div class="form-floating">
                            {{ form_animal.especie }}
                            <label for="id_especie">Espécie</label>
                        </div>
                    </div>
                </div>
                <div class="col mt-3 ">
                    <label for="animal_imagem">Selecione as imagens:</label>
                    <input class="form-control mt-2" type="file" name="animal_imagem" multiple required>
                </div>
                <div class="mt-4 text-center">
                    <button class="btn btn-outline-primary" type="submit" style="width: 150px;">Cadastrar</button>
                </div>
            </form>
        </div>
    </div>
</div>

<a class="btn btn-outline-primary m-4" href="{% url 'home:home' %}" role="button">Voltar a home</a>

{% endblock %}

templates/templates_cadastroanimal/detalhe_animal.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}

{% block title %}
Detalho do {{ animal.nome }}
{% endblock %}

{% block content %}

    <div class="container-fluid p-4 d-flex flex-column min-vh-100 fs-4">
        <h1 class="display-6">Detalhes do <strong>{{ animal.nome|capfirst }}</strong></h1>
    
        <!-- Card de detalhes -->
        <div class="card detail-card">
            <div class="card-body">
                <div class="row g-6 align-items-center">
                    <!-- Coluna para a imagem principal -->
                    <div class="col-md-4 text-center">
                        {% if animal.galeria.first %}
                        <img src="{{ animal.galeria.first.imagem.url }}" alt="Imagem de {{ animal.nome }}"
                            class="img-fluid rounded" style="height: 100%; object-fit: cover;">
                        {% else %}
                        <img src="{% static 'img/default.png' %}" alt="Imagem padrão" class="img-fluid rounded"
                            style="height: 100%; object-fit: cover;">
                        {% endif %}
                    </div>
    
                    <!-- Coluna para os detalhes -->
                    <div class="col-md-8 pt-4">
                        <p class="card-text"><strong>Nome:</strong> {{ animal.nome|capfirst }}</p>
                        <p class="card-text"><strong>Idade:</strong> {{ animal.idade }} anos</p>
                        <p class="card-text"><strong>Sexo:</strong> {{ animal.sexo|capfirst }}</p>
                        <p class="card-text"><strong>Espécie:</strong> {{ animal.especie|capfirst }}</p>
    
                        
                        <!-- Botão de adoção -->
                     <div class="d-flex justify-content-start">
                        <div class="status-adocao mx-3">
                            <a href="{% url 'cadastro_animal:detalhe_animal' animal.id %}" class="btn btn-outline-primary">Ver status da adoção </a>
                        </div>
                        <div class=" mx-3">
                            <a href="{% url 'adocao_gestao:adote' %}" class="btn btn-outline-success">Adotar <strong>{{ animal.nome|capfirst }}</strong> </a>
                        </div>
                   </div>


                    </div>
                </div>
            </div>
    
            <!-- Header com data de criação -->
            <div class="card-header ">
                <p class="card-text texto-criacao"><small class="text-muted">Criado em: {{ animal.data_criacao|date:"d/m/Y" }}</small></p>
            </div>
        </div>
     <!-- Galeria de fotos (excluindo a primeira imagem) -->
     <div class="p-4">
        <h2>Galeria de Fotos</h2>
        <div class="d-flex flex-wrap justify-content-start">
            {% for item in animal.galeria.all %}
            {% if not forloop.first %}
            <img src="{{ item.imagem.url }}" alt="{{ item.imagem.url }}" class="img-fluid rounded gallery-img">
            {% endif %}
            {% endfor %}
        </div>
    </div>


</div>
</div>
{% endblock %}

templates/templates_cadastroanimal/lista_animais.html
{% extends 'base.html' %}
{% load bootstrap5 %}
{% load static %}
{% bootstrap_css %}

{% block title %}
Lista de animais disponíveis
{% endblock %}

{% block content %}
<div class="container my-4">
    <h1 class="text-center mb-4">Lista de Animais Cadastrados</h1>

    <div class="row g-4">
        {% for animal in animais %}
        <div class="col-12 col-md-6 col-lg-4">
            <div class="card h-100">
                {% if animal.galeria.first %}
                <img src="{{ animal.galeria.first.imagem.url }}" class="card-img-top" alt="Imagem de {{ animal.nome|capfirst }}" style="height: 200px; object-fit: cover;">
                {% else %}
                <img src="{% static 'img\default.png' %}" class="card-img-top" alt="Imagem de {{ animal.nome|capfirst }}" style="height: 150px; object-fit: cover;">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title display-6">{{ animal.nome|capfirst }}</h5>
                    <p class="card-text">{{ animal.idade }} anos | {{ animal.especie|capfirst }} | {{ animal.sexo|capfirst }}</p>

                     <!-- Botão de adoção -->
                     <div class="d-flex justify-content-start">
                        <div class="">
                            <a href="{% url 'cadastro_animal:detalhe_animal' animal.id %}" class="btn btn-outline-primary">Ver mais </a>
                        </div>
                        <div class="">
                            <a href="{% url 'adocao_gestao:adote' %}" class="btn btn-outline-success ms-3">Adotar</a>
                        </div>
                   </div>
                    
                </div>
            </div>
        </div>
        {% empty %}
        <p class="text-center">Nenhum animal cadastrado.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}